name: CI

# If you don't check in the `.firebaserc` file (like it's done in this project)
# you should expliticly set the `--project` flag for `firebase deploy`
# https://stackoverflow.com/questions/43817521/firebase-cli-no-project-is-currently-active

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: compile Angular app
      working-directory: ./mte
      run: |
        npm install
        npm run build
    - name: deploy compiled app to Firebase
      working-directory: ./mte
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --project mad-trick-explainer --token ${{ secrets.FIREBASE_TOKEN }}
    - name: run Cypress tests
      uses: cypress-io/github-action@v1
