name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
        working-directory: mte
      - name: Serve app in background
        run: npm start
        working-directory: mte